### ISSUE TITLE
Don't put semicolons at the end of lines

### ISSUE THREAD

**Issue by Beliavsky** [NicoClinco/Fortran-Mixed#1]
I suggest not putting semicolons at the end of lines, as you did at https://github.com/NicoClinco/Fortran-Mixed/blob/main/SPECTRAL_METHODS/Interpolant/src/apps/main.f90 . It is valid but redundant.

**Comment by NicoClinco** [comment]
Thank you Beliavsky for your suggestion. This comes from C++ ahah
